##########DO NOT EDIT THIS FILE########
#######################################

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import * from dvkey

class DataVerseML(object):   
    def __init__(self, verbose=0):
        if verbose > 0:
            print("DataverseML Loaded...")
        
        #w = interactive()
        
        
        import pandas as pd
        from sklearn import model_selection
        from sklearn.metrics import classification_report
        from sklearn.metrics import confusion_matrix
        from sklearn.metrics import accuracy_score
        from sklearn.linear_model import LogisticRegression
        from sklearn.tree import DecisionTreeClassifier
        from sklearn.neighbors import KNeighborsClassifier
        from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
        from sklearn.naive_bayes import GaussianNB
        from sklearn.svm import SVC
        import requests
        
        ####### TEMPORARY #######
        global API_KEY
        self.api_key = API_KEY 
        self.url = "https://dataverse.unc.edu/"
        #########################
        
        
    def set_url(self,url):
        self.url = url
        
    def get_url(self):
        return self.url
    
    def set_api_key(self, key):
        self.api_key = key
        
    def get_api_key(self):
        return self.api_key
    
    def f(self, x):
        return x

    
    
    